AWSTemplateFormatVersion: "2010-09-09"
Description: Provision of VPC

# パラメータ
Parameters:
  EnvTag:
    Type: String
    Description: Environment Name

  EnvIp:
    Type: String
    Description: secondary octet ip addr

  Prefix: 
    Type: String
    Description: prefix for tag name

    
  # KeyName:
  #   Type: AWS::SSM::Parameter::Name
  #   Default: "vpcname-test"

Resources:
  # VPCの作成
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Sub '10.${EnvIp}.0.0/16'
      Tags:
        - Key: Name
          Value: !Sub '${EnvTag}-${Prefix}-vpc'
    